MODEL:
  TYPE: swin_minivit_distill
  NAME: swin_tiny_patch4_window7_224_minivit
  DROP_PATH_RATE: 0.0
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7
MINIVIT:
  SEPARATE_LAYERNUM_LIST: [1, 1, 1, 1]